# Generated by Django 3.0.5 on 2021-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='url_imagen',
            field=models.ImageField(default='null', upload_to='vinos', verbose_name='Imágen'),
        ),
    ]
