# Generated by Django 3.0.5 on 2021-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_vino_url_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variedad',
            options={'verbose_name_plural': 'Variedades'},
        ),
        migrations.AlterField(
            model_name='vino',
            name='url_imagen',
            field=models.ImageField(default='null', upload_to='vinos', verbose_name='Imagen'),
        ),
    ]
