# Generated by Django 3.0.5 on 2021-08-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210817_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vino',
            name='url_imagen',
            field=models.URLField(),
        ),
    ]
